.travis.yml, Project.toml, README.md, REQUIRE, docs/Project.toml, docs/make.jl
=> #9 - Replace REQUIRE by Project.toml

src/matrix.jl
=> #7 - Parameterize matrix type in IntervalMatrix

src/exponential.jl, src/matrix.jl, test/runtests.jl
=> #8 #20 - Fix infinity-norm; rename to opnorm; add 1-norm

docs/src/lib/methods.md, src/matrix.jl, test/runtests.jl
=> #14 - Split into normal matrix and symmetric interval matrix

docs/src/lib/methods.md, src/matrix.jl, test/runtests.jl
=> #30 - Instance check of concrete matrix in interval matrix

Project.toml, docs/src/lib/methods.md, src/IntervalMatrices.jl, src/matrix.jl, test/runtests.jl
=> #27 - Function to sample a concrete matrix from an interval matrix

src/exponential.jl
Closes #12.
```julia
using IntervalMatrices, BenchmarkTools
m = IntervalMatrix([-1.1..0.9 -4.1.. -3.9; 3.9..4.1 -1.1..0.9])
@btime a_over = expm_overapproximation($m, 1.0, 4)
192.078 μs (817 allocations: 23.23 KiB)
173.777 μs (754 allocations: 21.06 KiB)
@btime a_over = expm_underapproximation($m, 1.0, 4)
154.541 μs (687 allocations: 20.02 KiB)
132.805 μs (623 allocations: 17.86 KiB)
```
=> #12 - Improve expm_overapproximation

src/exponential.jl
Closes #10.
The benefit is surprisingly small (at least on a 2D example).
```julia
using IntervalMatrices, BenchmarkTools
m = IntervalMatrix([-1.1..0.9 -4.1.. -3.9; 3.9..4.1 -1.1..0.9])
@btime expm_overapproximation($m, 1.0, 4)
183.355 μs (817 allocations: 23.23 KiB)  # master
183.655 μs (811 allocations: 23.08 KiB)
@btime expm_underapproximation($m, 1.0, 4)
148.511 μs (687 allocations: 20.02 KiB)  # master
147.615 μs (681 allocations: 19.86 KiB)  # this branch
```
=> #10 - Improve quadratic_expansion

src/IntervalMatrices.jl, src/matrix.jl, src/matrix_arithmetic.jl, test/runtests.jl
=> #34 - Interval multiplication with interval matrix

docs/src/lib/methods.md, src/IntervalMatrices.jl, src/correction_hull.jl, src/exponential.jl, test/runtests.jl
Closes #2.
Closes #28.
~Requires: ~#34~
I did not export the functions because I consider them application-specific and not of general interest.
=> #28 - Correction hull

src/matrix.jl, test/runtests.jl
=> #55 - Add copy method

src/exponential.jl
=> #68 - Improve exponential remainder estimation

src/arithmetic.jl, test/runtests.jl
=> #81 - Overload subtraction

docs/src/index.md
Closes https://github.com/JuliaReach/IntervalMatrices.jl/issues/67.
=> #67 - Update references

src/arithmetic.jl, test/runtests.jl
=> Overload common arithmetic operations between interval matrices and non-interval matrices

docs/src/lib/methods.md, src/IntervalMatrices.jl, src/correction_matrices.jl, src/exponential.jl, test/runtests.jl
=> #99 - Rename expm functions

src/matrix.jl
=> #93 - Change default in rand

src/matrix.jl
=> #101 - Undef initializer 

src/matrix.jl
=> #69 - Add constructor for center and symmetric part

src/correction_matrices.jl, src/exponential.jl
=> #114 - Use square in exp overapproximation

src/correction_matrices.jl, src/exponential.jl, src/matrix.jl
=> #108 - Simplify constructor usages

src/power.jl, test/runtests.jl
~This branch is based on #129.~
```julia
julia> using IntervalMatrices
julia> A = rand(IntervalMatrix)
julia> pow1 = IntervalMatrixPower(A)
julia> pow2 = IntervalMatrixPower(A)
julia> pow3 = IntervalMatrixPower(A)
julia> for i in 1:10
B1 = increment!(pow1, algorithm="multiply")
B2 = increment!(pow2, algorithm="power")
B3 = increment!(pow3, algorithm="intersect")
println(diam(B1))
println(diam(B2))
println(diam(B3))
println(B1 == B3)
end
[2.4679109994429074 1.5579742283780835; 2.4942570188267292 0.8419249153888634]
[2.4679109994429074 1.5579742283780835; 2.4942570188267292 0.8419249153888634]
[2.4679109994429074 1.5579742283780835; 2.4942570188267292 0.8419249153888634]
true
[6.772049924686463 2.042596426017624; 4.266274790010085 1.841201844306318]
[6.772049924686463 2.6664688542539925; …
```
=> Add algorithms to IntervalMatrixPower

src/power.jl, test/runtests.jl
This fixes the algorithm added in #134.
=> Fix sqrt algorithm and rename it (matrix power)

src/power.jl
~This branch is based on #140.~
=> Make intersect algorithm (matrix power) more precise

src/correction_matrices.jl, test/runtests.jl
=> Add correction hull for a scalar matrix

Project.toml, src/matrix.jl, test/runtests.jl
Updates the two input constructor to be coherent to IA behavior
```julia
julia> A
2×2 Matrix{Int64}:
1  2
3  4
julia> B
2×2 Matrix{Int64}:
1  2
4  5
julia> IntervalMatrix(A, B)
ERROR: MethodError: no method matching atomic(::Type{Interval{Int64}}, ::Interval{Float64})
Closest candidates are:
atomic(::Type{Interval{T}}, ::T) where T<:Integer at C:\Users\lucaa\.julia\packages\IntervalArithmetic\uEztL\src\intervals\conversion.jl:72
atomic(::Type{Interval{T}}, ::Interval) where T<:AbstractFloat at C:\Users\lucaa\.julia\packages\IntervalArithmetic\uEztL\src\intervals\conversion.jl:122
atomic(::Type{Interval{T}}, ::S) where {T<:AbstractFloat, S<:Real} at C:\Users\lucaa\.julia\packages\IntervalArithmetic\uEztL\src\intervals\conversion.jl:79
Stacktrace:
[1] …
```
=> updated 2 inputs constructor

docs/src/lib/methods.md, src/IntervalMatrices.jl, src/exponential.jl, test/exponential.jl
=> Refactor exp methods

test/constructors.jl, test/exponential.jl, test/setops.jl
The bug in `JuliaFormatter` was fixed. This PR finishes the leftovers from #209.
=> Format test code

.github/workflows/CompatHelper.yml, docs/Project.toml, test/Project.toml
=> Fix compat for PkgVersion in tests; freeze IntervalArithmetic in docs

README.md
=> #199 - Add Zenodo badge to README

src/operations/arithmetic.jl
=> Fix ambiguities with `\`

src/operations/mult.jl, test/Aqua.jl
=> Fix ambiguities with matrix multiplication
