Project.toml

I accidentally copied the UUID from `LazySets` in #15 :astonished:

Replace wrong UUID

---

docs/src/index.md
src/arithmetic.jl
src/exponential.jl
test/runtests.jl

#51 - Matrix type not preserved in operations

---

docs/src/lib/methods.md
src/IntervalMatrices.jl
src/arithmetic.jl
test/runtests.jl

Closes #79.
To give some taste of the precision loss with normal multiplication:
```julia
julia> A = rand(IntervalMatrix)
2×2 IntervalMatrix{Float64,Interval{Float64},Array{Interval{Float64},2}}:
[-1.1446, 0.239556]  [-0.880356, -0.762082]
[-0.988057, 2.3486]   [0.363034, 1.13084]  
julia> A*A
2×2 IntervalMatrix{Float64,Interval{Float64},Array{Interval{Float64},2}}:
[-2.3418, 2.17994]  [-1.20644, 0.730987]
[-3.80552, 3.7868]  [-1.93581, 2.14863] 
julia> square(A)
2×2 IntervalMatrix{Float64,Interval{Float64},Array{Interval{Float64},2}}:
[-2.0676, 2.17994]  [-1.20644, 0.68805]
[-1.83557, 3.2185]  [-1.93581, 2.14863]
julia> diam(IntervalMatrix(A*A - square(A)))
2×2 Array{Float64,2}:
8.76926  3.8319 
12.6464   8.16887
julia> A*A*A*A
2×2 …
```

#79 - Matrix square

---

src/arithmetic.jl

The biggest speed difference comes from using `IntervalArithmetic.pow`. In the random examples that i tried, i didn't find differences in the size of the intervals.
```
n = 2
2
M = rand(IntervalMatrix, n, n)
3
@btime square($M)
3.366 μs (88 allocations: 3.89 KiB)
2×2 IntervalMatrix{Float64,Interval{Float64},Array{Interval{Float64},2}}:
[0.0409632, 4.74014]  [-1.66928, 5.37961]  
[-1.49507, 4.81819]     [0.0409632, 5.80631]
1
@btime square_v2($M)
162.732 ns (2 allocations: 160 bytes)
2×2 IntervalMatrix{Float64,Interval{Float64},Array{Interval{Float64},2}}:
[0.0409632, 4.74014]  [-1.66928, 5.37961]  
[-1.49507, 4.81819]     [0.0409632, 5.80631]
```

Faster square function

---

src/exponential.jl

#90 - Add quadratic expansion with scalars

---

.travis.yml

Closes #110.
I could not make both documentation and `allowed_failures` work together unless doing something like [this](https://github.com/JuliaReach/Reachability.jl/blob/bddd0e372fd4a533bbe5b0dcedc04603cdcd18fc/.travis.yml).

#110 - Fix docs building on Travis

---

src/matrix.jl

#49 - Convenience constructor for identity matrix

---

docs/src/lib/methods.md
src/arithmetic.jl
src/exponential.jl
test/runtests.jl

Closes #4.
This PR does not expose the algorithm to the API. That requires an extension of the interface with more algorithms and arguments.
Note that the scaling-and-squaring algorithm itself could become parametric in the algorithm for computing the (scaled) matrix exponential. It should be checked that this inner algorithm is not scaling-and-squaring again.
As a side note, I first wanted to write `@test underapp ⊆ overapp`, but that failed. So I guess at least one implementation is incorrect.
```julia
julia> overapp1 = exp_overapproximation(m, 1.0, 4)
2×2 IntervalMatrix{Float64,IntervalArithmetic.Interval{Float64},Array{IntervalArithmetic.Interval{Float64},2}}:
[-118.405, 126.84]   [-121.004, 131.545]
[-131.545, 121.004]  [-118.405, 126.84] 
julia> overapp2 = scale_and_square(m, 5, …
```

#4 - Implement scaling-and-squaring method

---

docs/src/lib/methods.md
docs/src/lib/types.md
src/IntervalMatrices.jl
src/power.jl

This is the first implementation for #94. More changes can be added later.

#94 - Symbolic interval matrix power type

---

src/matrix.jl

Closes #117.
Thanks to the fusing, the old version was already memory efficient. Still, taking the absolute has a (very) small performance impact.
```julia
julia> A = rand(IntervalMatrix, 100);
julia> @btime opnorm($A)  # this branch
44.356 μs (8 allocations: 234.64 KiB)
127.35643894432378
julia> @btime opnorm($A)  # master
45.334 μs (8 allocations: 234.64 KiB)
127.35643894432378
julia> B = IntervalMatrix(fill(Interval(-1.0), 100, 100));
julia> @btime opnorm($B)  # this branch
44.525 μs (8 allocations: 234.64 KiB)
100.0
julia> @btime opnorm($B)  # master
45.402 μs (8 allocations: 234.64 KiB)
100.0
julia> C = IntervalMatrix(fill(Interval(1.0), 100, 100));
julia> @btime opnorm($C)  # this branch
44.350 μs (8 allocations: 234.64 KiB)
100.0
julia> @btime opnorm($C)  # master
45.774 μs (8 …
```

#117 - Faster opnorm

---

src/exponential.jl
test/runtests.jl

This is the first step for #75. The proposed starting index `i0` is missing.
* first commit: just a refactoring of the old code (plus adding assertions `p < 2` that were not checked before)
* second commit: use the new `IntervalMatrixPower` type
* third commit: generalize code to nonnegative `p`
An example shows that the simple use of `square` in `IntervalMatrixPower` already pays off.
```julia
julia> A = rand(IntervalMatrix)
2×2 IntervalMatrix{Float64,Interval{Float64},Array{Interval{Float64},2}}:
[-0.152272, 1.1966]   [-0.340722, 1.00641]
[-0.688822, 1.30464]  [-1.08989, 2.67171]
julia> exp_overapproximation(A, 1.0, 10)  # master
2×2 IntervalMatrix{Float64,Interval{Float64},Array{Interval{Float64},2}}:
[-1.39748, 7.5724]   [-3.65965, 9.33968]
[-6.39121, 12.0942]  [-5.87441, 21.2407] …
```

#75 - Truncated exponential sum

---

src/power.jl
test/runtests.jl

Closes #131.
Currently the algorithm for the recursive call cannot be changed.

#131 - Matrix power via square decomposition, v2

---

src/matrix.jl

Closes #127.
---
```julia
julia> M = rand(IntervalMatrix, 100);
julia> opnorm(M, Inf)
128.9128489817419
julia> @btime opnorm($M, Inf) # master
23.559 μs (8 allocations: 234.64 KiB)
128.9128489817419
julia> @btime opnorm($M, Inf) # this branch
18.804 μs (0 allocations: 0 bytes)
128.9128489817419
julia> @btime opnorm($M, 1) # master
24.221 μs (8 allocations: 234.64 KiB)
130.11834643451667
julia> @btime opnorm($M, 1) # this branch
17.752 μs (0 allocations: 0 bytes)
130.11834643451667
```

#127 - Faster opnorm, part 2

---

docs/src/lib/methods.md
src/exponential.jl
test/runtests.jl

This is basically the implementation by @mforets [here](https://nbviewer.jupyter.org/github/mforets/escritoire/blob/master/2020/Week7/IM_Horner.ipynb).
(I observed that at some point the exponential remainder starts growing again, but this is not a problem of this PR → #145.)
```julia
julia> m = IntervalMatrix([-1.1..0.9 -4.1.. -3.9; 3.9..4.1 -1.1..0.9]);
julia> for K in [4, 6, 8, 20, 30]
H = horner_scheme(m, K)
end
K: 4
H: Interval{Float64}[[-6.59711, 16.4024] [-4.60191, 16.6734]; [-16.6734, 4.60191] [-6.59711, 16.4024]]
R: Interval{Float64}[[-107.653, 107.653] [-107.653, 107.653]; [-107.653, 107.653] [-107.653, 107.653]]
result: Interval{Float64}[[-114.25, 124.055] [-112.255, 124.326]; [-124.326, 112.255] [-114.25, 124.055]]
diam: [238.30443375030262 236.58025875030262; …
```

Add Horner scheme

---

.gitignore
Project.toml
src/matrix.jl
test/runtests.jl

Summary of the PR
- Implemented fallback from U, now it computes the hull of interval matrices, similar to what it does in `IntervalArithmetic.jl`. Should I also add `hull`? So in IntervalArithmetic, `hull` and `U` are synonyms (fixes #168 )
- Extended C (is strictly subset) from interval linear algebra, this is sometimes needed e.g. in verified algorithms such as epsilon inflation
- Fixed intersection of interval matrices (fixes #169 )
- Fixed real valued function (mid, diam, inf, etc.) to preserve the structure of the matrix (fixes #167 )
This seems to introduce a failure for interval matrix exponential, I need to investigate that.

added missing functions (radius, issubset) and fixes in real-valued functions

---

src/exponential.jl
test/runtests.jl

fixes #109 
With a quick look at the `exponential.jl` file, that function isn't used anywhere else anyway?

overestimation free quadratic expansion

---

src/matrix.jl
src/operations/numops.jl
test/constructors.jl

added constructor for complex interval matrices

---

Project.toml
docs/Project.toml
docs/src/index.md
src/IntervalMatrices.jl
src/affine.jl
src/matrix.jl
src/operations/mult.jl
src/operations/power.jl
src/operations/setops.jl
test/Project.toml
test/affine.jl
test/arithmetic.jl
test/constructors.jl
test/exponential.jl
test/runtests.jl
test/setops.jl

Closes #224.
I suggest to make a new v0.10 release when merged.
The main changes are:
- Use `interval` instead of `..` (first commit).
- Define some removed interval functions; see `src/IntervalMatrices.jl` (`intersect`, `in`, `==` for matrices, `±` for numbers).
- `:fast` multiplication does not work anymore because `SetRounding` was removed in `IntervalArithmetic`. Corresponding tests are deactivated. A docstring had to be changed because the intervals get tighter with the `:slow` algorithm.
- `\` does not work anymore because the default implementation via LU decomposition is not supported. Corresponding tests are deactivated.
- `IntervalArithmetic` v0.22 is not used for building the docs (the new decorations are not great to display IMO).

Support IntervalArithmetic v0.22

---

src/IntervalMatrices.jl
src/exponential.jl
src/matrix.jl
src/operations/setops.jl

Fix some piracies

---

test/affine.jl
test/arithmetic.jl
test/constructors.jl
test/exponential.jl
test/runtests.jl
test/setops.jl

This avoids a warning in the tests about a method redefinition.

Avoid redefinition of '==' in tests

---

src/IntervalMatrices.jl
src/init_IntervalArithmetic.jl
src/operations/mult.jl
test/arithmetic.jl
test/constructors.jl
test/intervals.jl
test/runtests.jl

~The first commit is from #233.~

Outsource init code and add tests for IntervalArithmetic; unsupport :fast multiplication

---

docs/src/lib/methods.md
src/IntervalMatrices.jl
src/operations/power.jl
test/exponential.jl

Reason: `get` is a `Base` function and has a somewhat different meaning associated.
This is a breaking change.

Rename `get` -> `matrix`

---

src/init_IntervalArithmetic.jl
src/matrix.jl
test/Aqua.jl
test/affine.jl
test/arithmetic.jl
test/intervals.jl
test/runtests.jl
test/setops.jl

Remove piracy for `==`

---

src/matrix.jl

The spelling "parametrized" is actually widely accepted. We can alternatively add it to the ignored words. But I do not mind using the slightly longer version, so that is what this PR proposes.

Consistent spelling
